name: Build ZManga APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Recreate Android folder with v2 embedding
        run: |
          rm -rf android
          flutter create --platforms android .

      - name: Add INTERNET permission
        run: |
          sed -i '/<manifest/a\    <uses-permission android:name="android.permission.INTERNET"/>' android/app/src/main/AndroidManifest.xml

      - name: Get dependencies
        run: flutter pub get

      - name: Build APKs (arm64-v8a + armeabi-v7a)
        run: flutter build apk --release --target-platform android-arm,android-arm64

      - name: Upload both APKs
        uses: actions/upload-artifact@v4
        with:
          name: ZManga-APKs
          path: build/app/outputs/flutter-apk/app-*-release.apk